// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWpix7rKzeDK9Geq0FlP2MhFMeGo9EKhw',
    appId: '1:1023345209468:web:0549262587251406c6d9f9',
    messagingSenderId: '1023345209468',
    projectId: 'ashrafyehiaclinic',
    authDomain: 'ashrafyehiaclinic.firebaseapp.com',
    databaseURL: 'https://ashrafyehiaclinic-default-rtdb.firebaseio.com',
    storageBucket: 'ashrafyehiaclinic.firebasestorage.app',
    measurementId: 'G-RQ2QCR2Y9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmoBOQZcHrqzoFEYkN3_rrqW1Dh3e-yiE',
    appId: '1:1023345209468:android:1fc86b8d09ce4573c6d9f9',
    messagingSenderId: '1023345209468',
    projectId: 'ashrafyehiaclinic',
    databaseURL: 'https://ashrafyehiaclinic-default-rtdb.firebaseio.com',
    storageBucket: 'ashrafyehiaclinic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOFg_NRgFFViPD6z9f2BeF5G_7Vj-E0yc',
    appId: '1:1023345209468:ios:8a5ea496b7d8fd67c6d9f9',
    messagingSenderId: '1023345209468',
    projectId: 'ashrafyehiaclinic',
    databaseURL: 'https://ashrafyehiaclinic-default-rtdb.firebaseio.com',
    storageBucket: 'ashrafyehiaclinic.firebasestorage.app',
    iosBundleId: 'com.example.drAshrafClinic',
  );
}
